authentik:
    secret_key: "PleaseGenerateASecurePleaseGenerateASecureKey@123!"
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
        enabled: false
    disable_update_check: true
    disable_startup_analytics: true        
    postgresql:
        password: "PleaseGenerateASecurePleaseGenerateASecureKey@123!"

server:
    ingress:
        # Specify kubernetes ingress controller class name
        ingressClassName: traefik
        enabled: true
        hosts:
            - authentik.domain.tld

postgresql:
    enabled: true
    auth:
        password: "PleaseGenerateASecurePleaseGenerateASecureKey@123!"
redis:
    enabled: true
