name = "kv-api"
main = "src/index.ts"
compatibility_date = "2023-11-21"

[[kv_namespaces]]
binding = "KV"
id = "fcd2c3d223ef49e2b81eeab2a54a3fba"

# wrangler.toml (wrangler v3.78.6^)
[observability]
enabled = true
