name = "guppy-api"
main = "src/index.ts"
minify = true
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
vars = { ENVIRONMENT = "development" }

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "guppy-db-development"
database_id = "4f9dada0-4da7-4794-a167-ef73eb666908"

[[kv_namespaces]]
binding = "KV"
id = "732f400c57184569b1923135b41b1450"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "guppy-vector-development"

[env.staging]
workers_dev = true
vars = { ENVIRONMENT = "staging" }
durable_objects.bindings = [
  {name = "COUNTER", class_name = "Counter"},
	{name = "WEBHOOK_RECEIVER", class_name = "WebhookReceiver"},
]
migrations = [
  {tag = "v1", new_sqlite_classes = ["Counter"]},
  {tag = "v1", new_sqlite_classes = ["WebhookReceiver"]},
]

[env.staging.ai]
binding = "AI"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "guppy-db-staging"
database_id = "7ea075db-e0cc-4a7a-bd35-33f13827e3d0"

[[env.staging.kv_namespaces]]
binding = "KV"
id = "87a1f59c5a194e2789d9ffac22e9bd38"

[[env.staging.vectorize]]
binding = "VECTORIZE"
index_name = "guppy-vector-staging"

[env.production]
workers_dev = true
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "guppy-db-production"
database_id = "0958528c-91a1-4c34-8e14-b805513600a4"

[[env.production.kv_namespaces]]
binding = "KV"
id = "024cb8ce59f8466daef9e7c5d6058a4e"

[[env.production.d1_databases]]
binding = "DB_CLI"
database_name = "guppy-db-cli"
database_id = "bce13a19-6d4b-4a11-9aaa-87606a1343a0"

[[env.production.kv_namespaces]]
binding = "KV"
id = "87a1f59c5a194e2789d9ffac22e9bd38"

[[env.production.vectorize]]
binding = "VECTORIZE"
index_name = "guppy-vector-production"
