name: deploy-worker-staging

on:
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'                
        
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "api"
          environment: "staging"
          preCommands: |
            echo "*** pre commands ***"
            wrangler vectorize create guppy-vector-staging --dimensions=768 --metric=cosine
          #  wrangler vectorize delete guppy-vector-staging          
          #  echo "******"          
          postCommands: |
            echo "*** post commands ***"
            wrangler d1 execute guppy-db-staging --file ./data/scripts.sql --remote 
            echo "******"          
