name: Deploy Worker Product

on:
  workflow_dispatch:
    inputs:
      working_directory:
        description: 'Select the working directory'
        required: true
        default: 'product'
        type: choice
        options:
          - northwind
          - product
          - kv
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'                
        
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "${{ github.event.inputs.working_directory }}-api"        
          postCommands: |
            echo "*** post commands ***"
            wrangler d1 execute ${{ github.event.inputs.working_directory }} --file ./data/${{ github.event.inputs.working_directory }}.sql --remote 
            echo "******"          
