name: Deploy Blazor Prod

on:
  workflow_dispatch:

jobs:
  commit-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Git
      run: |
        git config --global user.name "casaterraneo"
        git config --global user.email "casa.terraneo@gmail.com"      

    - name: Fetch all branches
      run: git fetch --all

    - name: Checkout production branch
      run: git checkout production

    - name: Merge main into production
      run: |
        git merge -X theirs main --allow-unrelated-histories --commit -m "Merge branch 'main' into production"

    - name: Remove files deleted in main branch
      run: |
          git checkout main -- . # Checkout all changes from main
          git clean -f -d        # Remove untracked files and directories
          git commit -am "Remove files that no longer exist in main"
  
    - name: Force push changes to production
      run: git push origin production --force
