name: Deploy Blazor Test

on:
  workflow_dispatch:  # Avvio manuale

jobs:
  commit-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Git
      run: |
        git config --global user.name "casaterraneo"
        git config --global user.email "casa.terraneo@gmail.com"      

    - name: Fetch all branches
      run: git fetch --all

    - name: Checkout staging branch
      run: git checkout staging

    - name: Merge main into staging
      run: |
        git merge -X theirs main --allow-unrelated-histories --commit -m "Merge branch 'main' into staging"
        git push origin staging
