name: Deploy Blazor Test

on:
  workflow_dispatch:

jobs:
  commit-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Git
      run: |
        git config --global user.name "casaterraneo"
        git config --global user.email "casa.terraneo@gmail.com"      

    - name: Fetch all branches
      run: git fetch --all

    - name: Delete staging branch from remote
      run: |
        git push origin --delete staging || echo "Production branch doesn't exist"

    - name: Create new staging branch from main
      run: |
        git checkout main
        git checkout -b staging

    - name: Push new staging branch to remote
      run: git push origin staging --force