name: Deploy Blazor Prod

on:
  workflow_dispatch:

jobs:
  commit-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Git
      run: |
        git config --global user.name "casaterraneo"
        git config --global user.email "casa.terraneo@gmail.com"      

    - name: Fetch all branches
      run: git fetch --all

    - name: Checkout production branch
      run: git checkout production

    - name: Merge main into production
      run: |
        git merge -X theirs main --allow-unrelated-histories --commit -m "Merge branch 'main' into production"

    - name: Force delete files that are not in the main branch
      run: git ls-files -d | xargs git rm
  
    - name: Force push changes to production
      run: git push origin production --force
