name: Deploy Blazor Dev

on:
  workflow_dispatch:

jobs:
  commit-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Git
      run: |
        git config --global user.name "casaterraneo"
        git config --global user.email "casa.terraneo@gmail.com"      

    - name: Fetch all branches
      run: git fetch --all

    - name: Delete development branch from remote
      run: |
        git push origin --delete development || echo "Development branch doesn't exist"

    - name: Create new development branch from main
      run: |
        git checkout main
        git checkout -b development

    - name: Push new development branch to remote
      run: git push origin development --force