name: Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Guppy version number to use (e.g. 0.1.0, 0.1.0-rc1, edge). Defaults to edge."
        required: false
        default: "edge"
        type: string        
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule: # Run every day at 12 PM
    - cron: "0 12 * * *"
env:
  RUN_IDENTIFIER: samplestest-${{ github.run_id }}-${{ github.run_attempt }}
jobs:
  test:
    name: Sample tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!
